name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call: {}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clj-${{ hashFiles('deps.edn') }}
          restore-keys: clj-

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: Unit tests
        run: clojure -M:test unit

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: target/test-results/

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clj-${{ hashFiles('deps.edn') }}
          restore-keys: clj-

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: Integration tests
        run: clojure -M:test integration

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: target/test-results/

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: clj-${{ hashFiles('deps.edn') }}
          restore-keys: clj-

      - uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: latest

      - name: E2E tests
        run: clojure -M:test e2e

      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: target/test-results/
